#ifndef __DIPLOMA_PROTOCOL_H
#define __DIPLOMA_PROTOCOL_H

#define PROTOCOL_NEW_CONNECTION 10 // Client request
#define PROTOCOL_ASSIGN_CONNECTION_IDX 11 // Server send connection idx
#define PROTOCOL_USER_LIST 12
#define PROTOCOL_FRAME 20
#define PROTOCOL_FRAME_AUDIO 21
#define PROTOCOL_FRAME_ACK 30
#define PROTOCOL_FRAME_NACK 31
#define PROTOCOL_CALL_REQUEST 40
#define PROTOCOL_CALL_CANCEL 42
#define PROTOCOL_CALL_ACCEPT 43
#define PROTOCOL_CALL_REJECT 44

#define FRAME_FLAG_EOF 1

#define PROTOCOL_NEW_CONNECTION_SIZE 65
#define USERNAME_SIZE 64
#define USERNAME_ENTRY_SIZE 66 // USERNAME_SIZE + idx 2 bytes
#define PROTOCOL_CALL_REQUEST_SIZE 5
#define PROTOCOL_CALL_CANCEL_SIZE 5
#define PROTOCOL_CALL_ACCEPT_SIZE 5

#endif
